### ISSUE TITLE
Help - In App Chat

### ISSUE THREAD

**Issue by bbhagat** [happyfoxinc/helpstack#49]
First of all a huge thanks for such a superb library. 

I had a question around how to integrate in app chat. I guess it always require one of the help desk solutions to be integrated? Is my assumption correct?

Regards,
Bhavik

**Comment by mosn** [comment]
@bbhagat I would also love to know if the in app chat is supported for email platform

**Comment by luckydev** [comment]
@bbhagat You can use HappyFox, ZenDesk, Desk.com or Vanilla email with HelpStack. 

@mosn Chat option is available only in HelpDesk integrations. For Emails, HelpStack will simply open Mail composer. Your conversation with app user will happen in Email app and not inside HelpStack. 

Please check https://github.com/happyfoxinc/helpstack/blob/master/README.md#configuring-helpstack-gears for available options.
