### ISSUE TITLE
AFNetworking 3

### ISSUE THREAD

**Issue by rez1dent3** [happyfoxinc/helpstack#50]
[!] Unable to satisfy the following requirements:
- `AFNetworking (~> 3.0)` required by `Podfile`
- `AFNetworking (~> 2.0)` required by `HelpStack (1.0)`

**Comment by hoandesign** [comment]
Please fix soon. Apple now request IPV6 for all of apps.

**Comment by ppaulojr** [comment]
I sometimes feel this is an AbandonWare I have three PR open for a long time, one is an annoying crash (https://github.com/happyfoxinc/helpstack/pull/52) and I don't see it being fixed anytime soon. I'm not very hopeful to get AFNetworking3 in this project.

**Comment by hoandesign** [comment]
I just received a mail from them. A fix is coming soon.

**Comment by ppaulojr** [comment]
I don't have such hope ...
